jobs:
  build-and-test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      # ... other build steps
      - # Add the cuda-toolkit step here
      - name: Install CUDA Toolkit
        uses: jcfisher/cuda-toolkit@v1.4.1
        with:
          version: 11.8
      - name: Verify CUDA Installation
        run: nvcc --version  # Check if nvcc is available
